plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.147'
    id 'com.hypherionmc.modutils.modpublisher' version '2.1.8'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        fbi_swat_armors {
            sourceSet(sourceSets.main)
        }
    }
}

repositories {
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
}

dependencies {
    implementation "com.geckolib:geckolib-neoforge-${project.minecraft_version}:${project.geckolib_version}"
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

publisher {
    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSE_TOKEN")
        github System.getenv("GITHUB_TOKEN")
    }

    setCurseID("783585")
    setModrinthID("8TP2HioV")

    setVersionType("release")

    setChangelog(new File("${project.rootDir}/changelog.md").text)

    setProjectVersion("${project.semantic_version}-neoforge")

    setDisplayName("FBI And SWAT Armors ${project.semantic_version}")

    setGameVersions(project.minecraft_version)

    setLoaders("neoforge")

    setCurseEnvironment("both")

    setIsManualRelease(false)

    setArtifact("${project.rootDir}/build/libs/${project.archives_base_name}-${project.mod_version}.jar")

    setDisableMalwareScanner(true)

    setJavaVersions(JavaVersion.VERSION_25, 25)

    setDisableEmptyJarCheck(true)

    github {
        repo = "Pyrix25633/Fabric-Forge-FbiAndSwatArmors"
        tag = "${project.semantic_version}-neoforge"
        displayName = "FBI And SWAT Armors ${project.mod_version}"
        createTag = true
        createRelease = true
        updateRelease = true
        draft = false
        target = "neoforge"
    }

    modrinthDepends {
        required 'geckolib'
    }

    curseDepends {
        required 'geckolib'
    }
}
