# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=26.3
	loader_version=0.19.5
	geckolib_version=5.5.7

# Mod Properties
	semantic_version=1.0.5
	mod_version=26.3-1.0.5-fabric
	maven_group=net.rupyber_studios
	archives_base_name=fbi_swat_armors

# Dependencies
	fabric_version=0.161.0+26.3
