# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false

# Forge Properties
    minecraft_version = 26.3
    neo_version = 26.3.0.23-beta
    geckolib_version = 5.5.7

# Mod Properties
    semantic_version = 1.0.4
    mod_version = 26.3-1.0.4-neoforge
    maven_group = net.rupyber_studios
    archives_base_name = fbi_swat_armors
