license="GPL-3.0"

[[mods]]
modId="fbi_swat_armors"
version="26.3-1.0.5-neoforge"
displayName="FBI And SWAT Armors"
authors="Rupyber Studios, Pyrix25633, Ruken"
description='''Adds FBI and SWAT armors.'''

[[dependencies.fbi_swat_armors]]
modId="neoforge"
type="required"
versionRange="[26.3.0.23-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.fbi_swat_armors]]
modId="minecraft"
type="required"
versionRange="[26.3]"
ordering="NONE"
side="BOTH"

[[dependencies.fbi_swat_armors]]
modId="geckolib"
type="required"
versionRange="[5.5.7,)"
ordering="NONE"
side="BOTH"
